### ISSUE TITLE
Cross-Server Toons Causing Double Chat

### ISSUE THREAD

**Issue by Airopsguy** [AIE-Guild/GreenWall#104]
I have recently merged two guilds using Greenwall. Both guilds are on the same Server (Shadow Council (SC)). It IS a connected realm server with Black Water Raiders (BWR). Having no issue with chat as long as all the toons are from SC. When the toons are from BWR however, we get double chat messages from those BWR toons in the main guild on SC. Any ideas?

**Comment by mrogaski** [comment]
Check to make sure that the configuration has the correct, fully-qualified guild names.

https://github.com/AIE-Guild/GreenWall/wiki/Connected-Realms

If the config looks good and you still see the issue, send me the debug output and I'll have a look.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

Thanks!

**Comment by Airopsguy** [comment]
I sent the file to the email in the debugging process you sent me. Thanks for the assist.

**Comment by Airopsguy** [comment]
oops wrong button:)

**Comment by mrogaski** [comment]
I got the file, could you take another capture and enter the command "/gw dump" while you are capturing?  If you send that with a copy of the configuration from the guild info window, I should be able to figure out where the configuration is getting lost.

Thanks!

**Comment by Airopsguy** [comment]
Not sure exactly what's going on. The only thing I changed in the string last night was that I added the fully registered guild name. And I've logged off since then. There's no more double chat. Mysterious.

**Comment by mrogaski** [comment]
OK, closing this out for now.  Let me know if you see any other issues.

Thanks!
