### ISSUE TITLE
[1.8.0] Null tags in one co-guild

### ISSUE THREAD

**Issue by jjonessec** [AIE-Guild/GreenWall#106]
So we are linked fine, coms works great, for both general and Officer, however only one side sees the tag, the otherside sees <> how can we get this fixed so tagging works correctly.

**Comment by mrogaski** [comment]
Send the configuration to greenwall@aie-guild.org and I'll have a look.  If the communication is occurring, there's probably a typo in the guild info tab for the side that doesn't see the problem or a problem with the code to parse the configuration.

**Comment by mrogaski** [comment]
Config received via e-mail.

**Comment by mrogaski** [comment]
Two requests sent for further information, no response.

**Comment by jjonessec** [comment]
I sent everything requested never recieved a response


Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Mark Rogaski <notifications@github.com> Date: 11/4/16  11:03 PM  (GMT-05:00) To: AIE-Guild/GreenWall <GreenWall@noreply.github.com> Cc: jjonessec <jjonessec@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [AIE-Guild/GreenWall] [1.8.0] Null tags in one co-guild (#106) 
Closed #106.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AIE-Guild/GreenWall","title":"AIE-Guild/GreenWall","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AIE-Guild/GreenWall"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #106."}],"action":{"name":"View Issue","url":"https://github.com/AIE-Guild/GreenWall/issues/106#event-848694638"}}}

**Comment by jjonessec** [comment]
No emails from you at requesting additional info other than my config which was sent. 8 requests  for updates and i recieved no responses.




Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Mark Rogaski <notifications@github.com> Date: 11/4/16  11:03 PM  (GMT-05:00) To: AIE-Guild/GreenWall <GreenWall@noreply.github.com> Cc: jjonessec <jjonessec@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [AIE-Guild/GreenWall] [1.8.0] Null tags in one co-guild (#106) 
Two requests sent for further information, no response.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AIE-Guild/GreenWall","title":"AIE-Guild/GreenWall","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AIE-Guild/GreenWall"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrogaski in #106: Two requests sent for further information, no response."}],"action":{"name":"View Issue","url":"https://github.com/AIE-Guild/GreenWall/issues/106#issuecomment-258587116"}}}

**Comment by mrogaski** [comment]
I only received an e-mail on the 19th of October, to which I sent the following response.

> Make sure that the FBK configuration is identical.  If it is, I'd need
the following information captured from each guild.
> 
> https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information
> 
> Thanks,
> Mark

I saw your post on Curse on the 23rd and [reposted it in the comments](https://mods.curse.com/addons/wow/greenwall?comment=238), since I figured the response may have gotten filtered.

If you can provide the information from both guilds, I can take a look.

Thanks,
Mark

**Comment by jjonessec** [comment]
The configuration are identical. ok will capture the info.


Sent from my Sprint Samsung Galaxy Note5.
-------- Original message --------From: Mark Rogaski <notifications@github.com> Date: 11/4/16  11:40 PM  (GMT-05:00) To: AIE-Guild/GreenWall <GreenWall@noreply.github.com> Cc: jjonessec <jjonessec@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [AIE-Guild/GreenWall] [1.8.0] Null tags in one co-guild (#106) 
I only received an e-mail on the 19th of October, to which I sent the following response.


Make sure that the FBK configuration is identical.  If it is, I'd need

the following information captured from each guild.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

Thanks,

Mark


I saw your post on Curse on the 23rd and reposted it in the comments, since I figured the response may have gotten filtered.

If you can provide the information from both guilds, I can take a look.

Thanks,

Mark

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AIE-Guild/GreenWall","title":"AIE-Guild/GreenWall","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AIE-Guild/GreenWall"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrogaski in #106: I only received an e-mail on the 19th of October, to which I sent the following response.\r\n\r\n\u003e Make sure that the FBK configuration is identical.  If it is, I'd need\r\nthe following information captured from each guild.\r\n\u003e \r\n\u003e https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information\r\n\u003e \r\n\u003e Thanks,\r\n\u003e Mark\r\n\r\nI saw your post on Curse on the 23rd and [reposted it in the comments](https://mods.curse.com/addons/wow/greenwall?comment=238), since I figured the response may have gotten filtered.\r\n\r\nIf you can provide the information from both guilds, I can take a look.\r\n\r\nThanks,\r\nMark"}],"action":{"name":"View Issue","url":"https://github.com/AIE-Guild/GreenWall/issues/106#issuecomment-258588506"}}}
