### ISSUE TITLE
Feature Request: Cross server communication

### ISSUE THREAD

**Issue by tattwamasi** [AIE-Guild/GreenWall#109]
If I understand the project correctly, there is currently no support for cross server (non connected realm) communication, for example between partner guilds on different servers, or guild which have transferred servers and now have the placeholder original guild, plus the new guild.

I understand the addon channel is limited to connected servers.  I found one abandoned addon that attempted to do cross server guild chat syncing via realID/BattleTag friends, tagged in the friend comment so the addon would know which to use.

Has there been any thought of adding such a feature to GreenWall?  I'm willing to help, but don't want to retread covered ground or reinvent any wheels.  For that matter, if anyone knows of other alternatives, I'd love to look at them too.

Thanks

**Comment by mrogaski** [comment]
The problem with using BNet as a transport is that it doesn't scale well for large guilds and it requires the use of "gateway" members to function as relays.  GreenWall's primary use case is for large guilds who don't want the resiliency and performance issue that comes with a gateway approach.  So there are no plans to implement non-connected realm communication with BNet chat.

The only add-on that does implement what you're looking for, that I know of is [FZ Cross-ream Communicator](https://mods.curse.com/addons/wow/fzxc).  I haven't used it, so I can't say how well it works.  It's not updated for 7.0.3, but it's been updated recently enough that I wouldn't consider it abandoned.
