### ISSUE TITLE
Update for WoW version 7.3.

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/GreenWall#115]
Patch day cometh ...

**Comment by Torsin** [comment]
Seems like there is an error:

Date: 2017-08-29 10:19:06
ID: 1
Error occured in: AddOn: GreenWall
Count: 2
Message: Error: AddOn GreenWall attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.
Debug:
   [C]: GuildControlSetRank()
   GreenWall\Utility.lua:221: IsOfficer()
   GreenWall\Config.lua:145: get_gm_officer_note()
   GreenWall\Config.lua:281: load()
   GreenWall\GreenWall.lua:589: GreenWall_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:

**Comment by mrogaski** [comment]
@Torsin See #116.  It's fixed in 1.8.5.

**Comment by Torsin** [comment]
Thanks @mrogaski I saw that earlier as well.
