### ISSUE TITLE
1.9 Alpha - Error when caging pet.

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#123]
Message: Interface\AddOns\GreenWall\Utility.lua:272: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: 01/01/18 10:56:16
Count: 2
Stack: Interface\AddOns\GreenWall\Utility.lua:272: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: ?
[C]: in function `GetItemInfo'
Interface\AddOns\GreenWall\Utility.lua:272: in function `IsLegendary'
Interface\AddOns\GreenWall\GreenWall.lua:264: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:

**Comment by mrogaski** [comment]
Do you have the full stack trace?

**Comment by ashayo** [comment]
That's the full error message.
It just needs some more nil checks. 
caged battlepets return Hbattlepet:, not item: , so item passed to IsLegendary is nul.
