### ISSUE TITLE
BfA Beta: SendAddonMessage faults

### ISSUE THREAD

**Issue by Tetsemi** [AIE-Guild/GreenWall#127]
When I do a /gw admin reload I get the following error

`1x GreenWall\Chat-Chat.lua:166: attempt to call global 'SendAddonMessage' (a nil value)
GreenWall\Chat-Chat.lua:166: in function `SendLocal'
GreenWall\GreenWall-1.9.0.lua:117: in function `?'
FrameXML\ChatFrame.lua:4565: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4233: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4269: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
type = 5
message = "reload"
opcode = "I"
payload = "I#reload"
(*temporary) = nil
(*temporary) = "GreenWall"
(*temporary) = "I#reload"
(*temporary) = "GUILD"
(*temporary) = "attempt to call global 'SendAddonMessage' (a nil value)"
`

**Comment by Tetsemi** [comment]
Also, this happens with /gw reset as well, it looks like due to the same global bug

`2x GreenWall\Chat-Chat.lua:166: attempt to call global 'SendAddonMessage' (a nil value)
GreenWall\Chat-Chat.lua:166: in function `SendLocal'
GreenWall\Channel-Channel.lua:211: in function `join'
GreenWall\Config.lua:361: in function `refresh_channels'
GreenWall\GreenWall-1.9.0.lua:464: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
type = 7
message = "officer"
opcode = "R"
payload = "R#officer"
(*temporary) = nil
(*temporary) = "GreenWall"
(*temporary) = "R#officer"
(*temporary) = "GUILD"
(*temporary) = "attempt to call global 'SendAddonMessage' (a nil value)"
`

**Comment by mrogaski** [comment]
The `SendAddonMessage` function appears to have been moved to the `C_ChatInfo` namespace.

**Comment by Tetsemi** [comment]
Confirmed fix, good to close, no lua errors now.
