### ISSUE TITLE
Greenwall failing to replicate player guild chat and officer chat messages

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/GreenWall#131]
It appears that a regression in the sender field for chat messages was introduced in 8.0.1.

> 	"2018-07-17 20:12:52 -- [debug/5@GreenWall.lua:254(GreenWall_OnEvent)] event=CHAT_MSG_GUILD, sender=Stigg, message=blah", -- [172]

The sender field is no longer fully qualified.  Because of the check for sender when replicating messages, players do no replicate their own guild and officer chat messages.

**Comment by mrogaski** [comment]
This appears to be fixed after the rollback of the Communities feature.

**Comment by Valeyard2** [comment]
And broken again now that communities are back. :(
