### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by illusaen** [AIE-Guild/GreenWall#136]
GreenWall seems to be using my character's old (pre-realm-transfer) name despite me deleting all SavedVariables and GreenWall itself and reinstalling.

**Comment by mrogaski** [comment]
Please capture debugging information using the following method.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

Thanks!

**Comment by mrogaski** [comment]
No further information.
