### ISSUE TITLE
can see greenwall chatters but they cant see me

### ISSUE THREAD

**Issue by Bullettimeman** [AIE-Guild/GreenWall#143]
Exactly as title says. Only bugs on one of my characters, i've tried uninstalling reinstalling, Disabling it, reenablng it. Deleting my wow wtf and addon folders. Tried disabling all addons but greenwall. And its only on one toon.

**Comment by Bullettimeman** [comment]
update: i'm now seeing stuff in a /4 channel but still cant be seen in guild chat

**Comment by mrogaski** [comment]
Please collect some debugging output while the issue is occurring.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

Thank you!

**Comment by Bullettimeman** [comment]
i just sent the email (:

**Comment by mrogaski** [comment]
[GreenWall.lua.txt](https://github.com/AIE-Guild/GreenWall/files/2298677/GreenWall.lua.txt)

**Comment by mrogaski** [comment]
![index](https://user-images.githubusercontent.com/1449231/44287941-a2ed5380-a23c-11e8-9919-4ce9b3cf2137.png)

**Comment by mrogaski** [comment]
I don't see any issues in the communication channel.  It appears everything is sent and received correctly.

**Comment by Bullettimeman** [comment]
Yea it fixed how idk how
