### ISSUE TITLE
GW not joining federation channel or parsing

### ISSUE THREAD

**Issue by Pentharian** [AIE-Guild/GreenWall#146]
After clean install or a /gw reset, GW does not join the federation channel. When manually entering the channel, all of the messages show up, though it is not parsed, and shows

[1. CHANNEL_NAME] [PLAYER]: C#%guild%## message.

Multiple computers, so likely something isolated to how my chat is being set up. No other chat addons installed.

**Comment by mrogaski** [comment]
Can you send a copy of the configuration you are using to greenwall@aie-guild.org?

Thanks!
