### ISSUE TITLE
GW Lua error

### ISSUE THREAD

**Issue by drakkon222** [AIE-Guild/GreenWall#148]
Haven't played for a few weeks. Didn't have this error before, so don't think it's a configuration issue. But it showed up today with no other addons enabled.

Message: Interface\AddOns\GreenWall\Config.lua:137: bad argument #1 to 'gsub' (string expected, got nil)
Time: Fri Sep 21 08:17:29 2018
Count: 1
Stack: Interface\AddOns\GreenWall\Config.lua:137: bad argument #1 to 'gsub' (string expected, got nil)
[C]: in function `gsub'
Interface\AddOns\GreenWall\Config.lua:137: in function `substitute'
Interface\AddOns\GreenWall\Config.lua:218: in function `load'
Interface\AddOns\GreenWall\GreenWall.lua:463: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "%$(%a)"
(*temporary) = <function> defined @Interface\AddOns\GreenWall\Config.lua:137
(*temporary) = "string expected, got nil"

**Comment by drakkon222** [comment]
Appears to be happening mainly when a guild member logs on or off. It was not fixed with the "system message pattern" fix in 1.9.8

**Comment by mrogaski** [comment]
Can you send a copy of your configuration to greenwall@aie-guild.org?

Thanks!

**Comment by drakkon222** [comment]
Turned out to be a configuration problem. Someone mistyped something in the guild info.
