### ISSUE TITLE
Error with the BFA 8.1 patch

### ISSUE THREAD

**Issue by teyasio** [AIE-Guild/GreenWall#149]
Every time guild chat gets used you get the following error
3x SendChatMessage(): Invalid escape code in chat message
[C]: ?
[C]: in function `SendChatMessage'
GreenWall\Channel-Channel.lua:363: in function `tl_flush'
GreenWall\Channel-Channel.lua:323: in function <GreenWall\Channel.lua:295>
(tail call): ?
GreenWall\GreenWall-1.9.8.lua:256: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = "C#DJ##|Kv1|k"
(*temporary) = "CHANNEL"
(*temporary) = nil
(*temporary) = "1"

**Comment by Torsin** [comment]
Debugging looks something like this:
```lua
	"2018-12-11 21:47:24 -- [debug/5@GreenWall.lua:254(GreenWall_OnEvent)] event=CHAT_MSG_GUILD, sender=Torsin-Proudmoore, message=|Kv38|k", -- [126]
	"2018-12-11 21:47:24 -- [debug/3@Channel.lua:275(send)] channel=0, type=1, message=|Kv38|k", -- [127]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:331(tl_enqueue)] enqueued segment: C#ICBG##|Kv38|k", -- [128]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:348(tl_flush)] servicing transmit queue; channel=0, 1 message(s) queued.", -- [129]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:126(is_connected)] checking number=0, name=<<468A>>", -- [130]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:118(is_configured)] number=0, name=<<468A>>, password=<<6F79>>, cversion=1, stale=false", -- [131]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:129(is_connected)] confirmed number=1, name=<<468A>>", -- [132]
	"2018-12-11 21:47:24 -- [debug/5@Channel.lua:340(tl_dequeue)] dequeued segment: C#ICBG##|Kv38|k", -- [133]
	"2018-12-11 21:47:24 -- [debug/4@Channel.lua:362(tl_flush)] channel=1, segment=C#ICBG##|Kv38|k", -- [134]
```

**Comment by ashayo** [comment]
Here's a temporary patch. Load this addon as well.
https://wow.curseforge.com/projects/gw-patch

**Comment by Torsin** [comment]
Although it fixes Guild chat, it doesn't touch officer chat.
