### ISSUE TITLE
Blank messages sent

### ISSUE THREAD

**Issue by PycelleAIE** [AIE-Guild/GreenWall#151]
Since the last GW update, everyone BUT my subguild have been receiving blank messages from me. The problem is intermittent. I haven't seen it happen with all my other addons disabled so far but I've been unable to isolate any of them as a potential cause.

Attaching a log here. On lines 14 and 52 I transmit a normal message. On lines 75 and 129, the code sees an empty message from me. I hadn't typed anything at the time.

I completely wiped and reinstalled all my addons which seemed to take care of the problem temporarily but it's back now.

[GreenWall Debug Log.txt](https://github.com/AIE-Guild/GreenWall/files/2719644/GreenWall.Debug.Log.txt)

**Comment by dijital20** [comment]
From my pretty elementary review of the code, one way we could stem this is to add code into send in Channel.lua to bail out of the message is empty. That might keep us from ever sending blank messages, which would be pretty useless to send anyway.

I do find it odd that in both of the lines @PycelleAIE references, the message sent is only a single quote. I gather there's no way to know the origin of the channel message (whether it was user-typed or generated from an addon)?

**Comment by mrogaski** [comment]
The beta for 1.9.10 is up on Curse.  This should fix the issue.

**Comment by PycelleAIE** [comment]
I'll check it out shortly, thanks stigg!

**Comment by PycelleAIE** [comment]
Code change is working perfectly so far. Can't thank you enough!
