### ISSUE TITLE
GW for v8.1.0 doesn't reflect correct member receiving legendary item

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#153]
Since the change to guild chat hooks in v8.1.0, when CHAT_MSG_LOOT event fires, message received by other players is "You receive item <item>" rather than stating the actual member receiving item.

**Comment by mrogaski** [comment]
Let me know if you can get a debug capture of this.

**Comment by ashayo** [comment]
sender:
	"2019-01-05 19:07:56 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_LOOT", -- [339]
	"2019-01-05 19:07:56 -- [debug/5@GreenWall.lua:288(GreenWall_OnEvent)] event=CHAT_MSG_LOOT, sender=Jekle-EarthenRing, message=You receive loot: |cff0070dd|Hitem:45087::::::::120:105::::::|h[Runed Orb]|h|r.", -- [340]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_LOOT", -- [341]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:288(GreenWall_OnEvent)] event=CHAT_MSG_LOOT, sender=Jekle-EarthenRing, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [342]
	"2019-01-05 19:07:57 -- [debug/3@Channel.lua:275(send)] channel=4, type=3, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [343]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:331(tl_enqueue)] enqueued segment: L#fidelis##You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [344]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:348(tl_flush)] servicing transmit queue; channel=4, 1 message(s) queued.", -- [345]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:126(is_connected)] checking number=4, name=<<0419>>", -- [346]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:118(is_configured)] number=4, name=<<0419>>, password=<<41FB>>, cversion=1, stale=false", -- [347]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:129(is_connected)] confirmed number=4, name=<<0419>>", -- [348]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:340(tl_dequeue)] dequeued segment: L#fidelis##You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [349]
	"2019-01-05 19:07:57 -- [debug/4@Channel.lua:362(tl_flush)] channel=4, segment=L#fidelis##You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [350]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_CHANNEL", -- [351]
	"2019-01-05 19:07:57 -- [debug/4@Channel.lua:445(tl_receive)] channel=4, sender=Jekle-EarthenRing, segment=L#fidelis##You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [352]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:452(tl_receive)] channel=4, tx_hash[0xBDC9] == 1", -- [353]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:467(tl_receive)] opcode=L, guild_id=fidelis, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [354]
	"2019-01-05 19:07:57 -- [debug/5@Channel.lua:425(al_decode)] type=3, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [355]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_LOOT", -- [356]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:288(GreenWall_OnEvent)] event=CHAT_MSG_LOOT, sender=Jekle-EarthenRing, message=You receive loot: |cffa335ee|Hitem:45256::::::::120:105::3::::|h[Twisted Visage]|h|r.", -- [357]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_LOOT", -- [358]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:288(GreenWall_OnEvent)] event=CHAT_MSG_LOOT, sender=Jekle-EarthenRing, message=You receive loot: |cffa335ee|Hitem:45246::::::::120:105::3::::|h[Golem-Shard Sticker]|h|r.", -- [359]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_SYSTEM", -- [360]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:395(GreenWall_OnEvent)] event=CHAT_MSG_SYSTEM, message=|cffff80ff|Htransmogappearance:21737|h[Golem-Shard Sticker]|h|r has been added to your appearance collection.", -- [361]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_LOOT", -- [362]
	"2019-01-05 19:07:57 -- [debug/5@GreenWall.lua:288(GreenWall_OnEvent)] event=CHAT_MSG_LOOT, sender=Jekle-EarthenRing, message=You receive loot: |cffa335ee|Hitem:45249::::::::120:105::3::::|h[Brass-Lined Boots]|h|r.", -- [363]


receiver:
	"2019-01-05 19:44:04 -- [debug/5@GreenWall.lua:237(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_CHANNEL", -- [1799]
	"2019-01-05 19:44:04 -- [debug/4@Channel.lua:445(tl_receive)] channel=2, sender=Jekle-EarthenRing, segment=L#fidelis##You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1800]
	"2019-01-05 19:44:04 -- [debug/5@Channel.lua:467(tl_receive)] opcode=L, guild_id=fidelis, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1801]
	"2019-01-05 19:44:04 -- [debug/5@Channel.lua:425(al_decode)] type=3, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1802]
	"2019-01-05 19:44:04 -- [debug/3@Channel.lua:403(receive)] channel=2, type=3, sender=Jekle-EarthenRing, guild=fidelis, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1803]
	"2019-01-05 19:44:04 -- [debug/5@Chat.lua:36] type=3, guild_id=fidelis, #content=1, #arglist=17", -- [1804]
	"2019-01-05 19:44:04 -- [debug/4@Chat.lua:114(ReplicateMessage)] event=LOOT, guild_id=fidelis, message=You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1805]
	"2019-01-05 19:44:04 -- [debug/5@Chat.lua:129(ReplicateMessage)] frame=ChatFrame1, event=LOOT, sender=Jekle-EarthenRing, message=<fidelis> You receive loot: |cffff8000|Hitem:45038::::::::120:105::::::|h[Fragment of Val'anyr]|h|r.", -- [1806]

**Comment by ashayo** [comment]
receiver:

![image](https://user-images.githubusercontent.com/9302684/50722449-44f5d580-1123-11e9-817f-bfdd563ff943.png)

**Comment by ashayo** [comment]
Looks good in v1.9.11beta
