### ISSUE TITLE
Not all legendary quality items broadcast correct message

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#156]
Legendary quality items that are not gear but other things like quest items (eg "Heart of Flame" report wrong message.

13:05:10 [Stealthgoat-EarthenRing]: L#libertas##You create: [Heart of Flame].
13:13:35 [Stealthgoat-EarthenRing]: A#libertas##%s has earned the achievement [Dragonwrath, Tarecgosa's Rest]!
13:13:35 [Stealthgoat-EarthenRing]: L#libertas##Stealthgoat-EarthenRing receives item: [Dragonwrath, Tarecgosa's Rest].

**Comment by ashayo** [comment]
Another example

11:53:21 [Murcielagos-AeriePeak]: L#omen##Murcielagos-AeriePeak receives item: [Awoken Titan Essence].
11:53:33 [Murcielagos-AeriePeak]: L#omen##Your [Raddon's Cascading Eyes] was changed to [Raddon's Cascading Eyes].
11:54:45 [Murcielagos-AeriePeak]: L#omen##Murcielagos-AeriePeak receives item: [Awoken Titan Essence].
11:55:06 [Murcielagos-AeriePeak]: L#omen##Your [Archimonde's Hatred Reborn] was changed to [Archimonde's Hatred Reborn].

**Comment by mrogaski** [comment]
@ashayo Is there any way  to get some debug output for one of these events?

**Comment by mrogaski** [comment]
Marking this a "won't fix" as achievements and loot announcements can't be supported after 8.2.5.
