### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by Bristol01** [AIE-Guild/GreenWall#170]
So my guild master and i have spent an hour today trying to figure out and set up greenwall, but
My chat is being spammed with " Connected to confederation on channel 4."
And my Guild Masters chat is being spammed with " Connected to confederation on channel 1"
plz help. This is what we have in the guild information.
GWc:The_Iron_Wolves:Wolves
GWp:The Iron Wolves-Area52:TIW
GWp:The Iron Wolves ll-Area52:TIWll

**Comment by mrogaski** [comment]
I don't believe underscores are permitted in channel names.

This might be better.

```
GWc:TheIronWolves:Wolves
GWp:The Iron Wolves-Area52:TIW
GWp:The Iron Wolves ll-Area52:TIWll
```

**Comment by Bristol01** [comment]
do they allow spaces, i forgot we took out the underscores but we do have spaces

**Comment by Bristol01** [comment]
Okay so we put that in the info and now im being spammed with a window saying to put in the password for the channel, but i cant even finish typing the password before the window resets itself

**Comment by mrogaski** [comment]
> 
> 
> Okay so we put that in the info and now im being spammed with a window saying to put in the password for the channel, but i cant even finish typing the password before the window resets itself

If the password for the channel was changed, another guild member might be keeping the channel open with the old password.  You can rename the channel to avoid the issue.
