### ISSUE TITLE
Greenwall Issue

### ISSUE THREAD

**Issue by themadtux** [AIE-Guild/GreenWall#172]
Anytime an event happens this pops up from Greenwall..

Message: Interface\AddOns\GreenWall\Utility.lua:135: attempt to index local 'name' (a nil value)
Time: Sat Nov  2 09:35:05 2019
Count: 4
Stack: Interface\AddOns\GreenWall\Utility.lua:135: attempt to index local 'name' (a nil value)
[C]: ?
Interface\AddOns\GreenWall\Utility.lua:135: in function `GlobalName'
Interface\AddOns\GreenWall\GreenWall.lua:426: in function `GreenWall_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: 

I've installed a new copy...  clearing my WTF folder and still happens.   Any ideas?

Thanks

**Comment by mrogaski** [comment]
I can't replicate the problem.  Can you capture for debugging output while the problem is occurring?

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

**Comment by themadtux** [comment]
Check your mail :) 

Thanks!

**Comment by mrogaski** [comment]
It looks like you have another add-on that's modifying the system messages.

A normal alert from the system looks like this.

> |Hplayer:Darkshott|h[Darkshott]|h has come online.

But in your logs, I see this.

> Raptorhill has come |cff298F00online|r.

If you have a custom UI, it's probably coloring the word "online".

The good thing is that this is something we can probably fix in a way that won't prevent you from using the UI with GreenWall.  But it may be a few days before I can get to it.

**Comment by themadtux** [comment]
Ok..  no worries.  Yeah I'm using Tukui w/ MaxUI and ElvUi w/ MerathilisUI ...  I'll search around and see if there is a modifier for that information. 

Thanks for the heads up!
