### ISSUE TITLE
Connection issue?

### ISSUE THREAD

**Issue by berkjerky** [AIE-Guild/GreenWall#188]
I've had this problem recently where people in the other connected guild can see what I type but I can't see what they type. The addon used to work fine and this just recently started happening. Disabled and re-enabled and also reinstalled and still hasn't been fixed.

**Comment by mrogaski** [comment]
We'll need more information to investigate.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

**Comment by berkjerky** [comment]
The issue has been fixed! Turns out the issue was that I also had WoW Instant Messenger installed and, by enabling the history function on WIM, they were clashing for some reason. I disabled WIM and Greenwall now works fine. Is there a possibility in the future of support so these addons can work simultaneously?

Thanks!
Desirée De Logé
________________________________
