### ISSUE TITLE
Spammy nonsense setting up new bridge

### ISSUE THREAD

**Issue by mltco78dhs** [AIE-Guild/GreenWall#197]
I'm setting up a bridge between two guilds on Blood Furnace.

One is "Horrid" the other is "Horrifying Damage".

This is what I have in the guild info box on both guilds:

```
grm^1;1;1;3;1;+;XX;XX;2;X^g
GWc:H-HDG:<Redacted>
GWp:Horrid-Blood Furnace:H
GWP:Horrifying Damage-Blood Furnace:HD
GWa:HOC:<Redacted>
```

As of right now I'm the only member in either guild with GreenWall and when I sign in on either of them I get an infinitely repeating spam line in chat like this:

```GreenWall: Connected to confederation on channel 5.```

Does GreenWall rely on someone being active and having the AddOn installed in both guilds (all guilds) in order for it to behave itself or do I have something wrong with my setup.

**Comment by mrogaski** [comment]
GreenWall must be installed to see messages from the other guilds or to have your messages in guild chat seen by other guilds. Things will function properly if no one is using it in another guild, they just won't see what you are saying.

I suspect the channel name you chose (`H-HDG`) is the problem, I don't believe hyphens are allowed.

**Comment by mltco78dhs** [comment]
I'll remove the hyphen and see what happens. Thanks.
