### ISSUE TITLE
10.1 update with Mixed Horde/alliance guilds

### ISSUE THREAD

**Issue by Cameroncodes92** [AIE-Guild/GreenWall#205]
Will it be possible to add alliance guilds to horde guilds within greenwall to communicate between guilds within the same server connections? 
If not, is this something being looked into?

**Comment by Tetsemi** [comment]
I did extensive testing with this on the PTR.  The biggest issue is that the custom chat channels, that Greenwall uses, are still faction specific.  So what you're going to end up with, if you have Horde and Alliance guilds both configured, the Horde characters will see only the direct guild communication and any Greenwall messages from Horde characters in other guilds, and the same for Alliance characters.

As for any work that's being done on Greenwall, I'll let the owner answer that..

**Comment by mrogaski** [comment]
To bridge between factions, you'd need to use BNet channels.  This would add a significant amount of complexity to the set-up and maintenance of the guild confederation.  Greenwall was not intended for this use case and won't be extended to support it.

The [XFaction](https://github.com/Chalsean/XFaction) add-on uses the BNet approach and is actively maintained.
