### ISSUE TITLE
Can I have two guild with the same name connected?

### ISSUE THREAD

**Issue by itzWebby1** [AIE-Guild/GreenWall#208]
We have part of our guild on another server and I can not get the addon to work properly.

GWc:DiscordKittenClub:DKC69
GWv:1.6.0
GWp:Discord Kitten Club:DKCSR
GWp:Discord Kitten Club:DKCMG

is what I have in the guild info on both guilds.

Also, am I able to have any additional information in the guild info or does it now have to only contain the greenwall stuff?

**Comment by mrogaski** [comment]
You need to use fully qualified names for each guild.

`GWp:Discord Kitten Club-Moon-Guard:DKCMG`

See the [Connected Realms](https://github.com/AIE-Guild/GreenWall/wiki/Connected-Realms) page for more details.

You can put other information in the guild info tab, as long as it's on separate lines.  But there is a limit to how much text you can add.

**Comment by itzWebby1** [comment]
I have a new issue for all my members saying that something is changing the message's appearance. A majority of us have elvui. I sent an email with the .lua file.

**Comment by itzWebby1** [comment]
"GreenWall: [ERROR] Message corruption detected.  Please disable add-ons that might modify messages on channel 4 " Email sent! Thank you

**Comment by itzWebby1** [comment]
"2023-06-15 16:19:12 -- event logging is turned ON.", -- [1]
	"2023-06-15 16:19:17 -- [ERROR] Message corruption detected.  Please disable add-ons that might modify messages on channel 4.", -- [2]
	"2023-06-15 16:22:38 -- debug/4 [@Interface/AddOns/GreenWall/Settings.lua:324:set] changed debug from \"0\" to \"5\" (account)", -- [3]
	"2023-06-15 16:22:38 -- debugging level is set to 5.", -- [4]
	"2023-06-15 16:22:38 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua:203:?] type=CHANNEL, message=\"\"", -- [5]
	"2023-06-15 16:22:40 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=GUILD_ROSTER_UPDATE", -- [6]
	"2023-06-15 16:22:40 -- debug/5 [@Interface/AddOns/GreenWall/Config.lua:148:load] configuration valid; skipping.", -- [7]
	"2023-06-15 16:22:42 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua:203:?] type=CHANNEL, message=\"Test\"", -- [8]
	"2023-06-15 16:22:42 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [9]
	"2023-06-15 16:22:42 -- debug/4 [@Interface/AddOns/GreenWall/Channel.lua:437:tl_receive] channel=4, sender=Paminra-Stormrage, segment=\"Test\"", -- [10]
	"2023-06-15 16:22:42 -- debug/2 [@Interface/AddOns/GreenWall/Channel.lua:450:tl_receive] channel=4, tx_hash[0x7724] not found", -- [11]
	"2023-06-15 16:22:42 -- [ERROR] Message corruption detected.  Please disable add-ons that might modify messages on channel 4.", -- [12]
	"2023-06-15 16:22:42 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:459:tl_receive] opcode=Test, guild_id=-, message=\"\"", -- [13]
	"2023-06-15 16:22:42 -- debug/2 [@Interface/AddOns/GreenWall/Channel.lua:475:tl_receive] unknown segment opcode: Test", -- [14]
	"2023-06-15 16:22:42 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:417:al_decode] type=0, message=\"\"", -- [15]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua:203:?] type=GUILD, message=\"Test again\"", -- [16]
	"2023-06-15 16:22:46 -- debug/3 [@Interface/AddOns/GreenWall/Channel.lua:272:send] channel=4, type=1, message=\"Test again\"", -- [17]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:323:tl_enqueue] enqueued segment: \"C#DKCSR##Test again\"", -- [18]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:340:tl_flush] servicing transmit queue; channel=4, 1 message(s) queued.", -- [19]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:126:is_connected] checking number=4, name=<<E62A>>", -- [20]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:118:is_configured] number=4, name=<<E62A>>, password=<<AD3A>>, cversion=1, stale=false", -- [21]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:129:is_connected] confirmed number=4, name=<<E62A>>", -- [22]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:332:tl_dequeue] dequeued segment: \"C#DKCSR##Test again\"", -- [23]
	"2023-06-15 16:22:46 -- debug/4 [@Interface/AddOns/GreenWall/Channel.lua:354:tl_flush] channel=4, segment=\"C#DKCSR##Test again\"", -- [24]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [25]
	"2023-06-15 16:22:46 -- debug/4 [@Interface/AddOns/GreenWall/Channel.lua:437:tl_receive] channel=4, sender=Paminra-Stormrage, segment=\"C#DKCSR##Test again\"", -- [26]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:444:tl_receive] channel=4, tx_hash[0x653E] == 1", -- [27]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:459:tl_receive] opcode=C, guild_id=DKCSR, message=\"Test again\"", -- [28]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/Channel.lua:417:al_decode] type=1, message=\"Test again\"", -- [29]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_GUILD", -- [30]
	"2023-06-15 16:22:46 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:284: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event=CHAT_MSG_GUILD, sender=Paminra-Stormrage, message=\"Test again\"", -- [31]
	"2023-06-15 16:22:49 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [32]
	"2023-06-15 16:22:54 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [33]
	"2023-06-15 16:22:56 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [34]
	"2023-06-15 16:23:05 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [35]
	"2023-06-15 16:23:06 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [36]
	"2023-06-15 16:23:06 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [37]
	"2023-06-15 16:23:10 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=CHAT_MSG_CHANNEL", -- [38]
	"2023-06-15 16:23:10 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua:203:?] type=GUILD, message=\"\"", -- [39]
	"2023-06-15 16:23:10 -- debug/5 [@Interface/AddOns/GreenWall/GreenWall.lua\"]:238: in function `GreenWall_OnEvent'\n[string \"*GreenWall.xml:33_OnEvent:1:GreenWall_OnEvent] event occurred; event=GUILD_ROSTER_UPDATE", -- [40]
	"2023-06-15 16:23:10 -- debug/5 [@Interface/AddOns/GreenWall/Config.lua:148:load] configuration valid; skipping.", -- [41]
	"2023-06-15 16:23:14 -- debug/3 [@Interface/AddOns/GreenWall/GreenWall.lua:100:?] command=debug, args=0", -- [42]
	"2023-06-15 16:23:14 -- debugging level is set to 0.",

**Comment by mrogaski** [comment]
Closing this, opened the other issue as #209.
