### ISSUE TITLE
WoW Retail 10.2.0 toc bump needed

### ISSUE THREAD

**Issue by Tetsemi** [AIE-Guild/GreenWall#210]
WoW just released 10.2.0 and the current .toc is 10.1.0

Please update when possible.

**Comment by mrogaski** [comment]
Released 261e48da9bc9106e880ac3675bf7f585299785ba, 1dbf105f8ed3b5a5efbf839624e430aef22ccb10, and 09b56e850fdebf3d957dedadc524eb114303121a.
