### ISSUE TITLE
Add possibility to have greenwall chat in separate chat window not as part of the regular guild chat

### ISSUE THREAD

**Issue by pekvasnovsky** [AIE-Guild/GreenWall#212]
Hello, great addon,

would it be possible to have the greenwall messages in a separate chat window?

maybe it would make sense that defaults could be defined in the bridge configuration?

so if guild wants, they can make all new participants to have the bridged chat in separate window or mixed with own guild chat
and then each person could just for the current bridge configuration override this setting to force mixed or force separate chat window

this way it would be possible to keep the individuality of the guild and also have the benefits of bridged guild chat

**Comment by pekvasnovsky** [comment]
yes that would be good for some small parties

the downside of this workaround is that there is no way to have it automatically moderated to allow only confederation members to participate (because if somebody leaves the guild they would still have access)

**Comment by ixidion** [comment]
> the downside of this workaround is that there is no way to have it automatically moderated to allow only confederation members to participate (because if somebody leaves the guild they would still have access)
Greenwall uses a chatchannel in the backround. Greenwall does not solve password change issues for you. You have to change the channelpassword/configuration regularly.

If you want that feature for yourself and not enforce it for the whole guild, you can use Prat-Addon with an inbound-filter on the Greenwall-Channel.

**Comment by mrogaski** [comment]
It seems to me that this is really a chat filtering problem and not a confederation problem, so it's outside the scope of GreenWall.  Additionally, splitting the local guild chat from the confederation guild chat traffic would likely introduce significant confusion if some members are viewing all traffic and others were looking at only the local traffic.

I'm going to decline this request, but if another add-on attempts to implement this on top of GreenWall I'm happy to consider minor changes to make the filtering easier.

**Comment by mrogaski** [comment]
At one point we did have channel defense, but channel bans were not very robust and we pulled out the feature for stability.  Currently, the security of the channel is bounded by the security of the guild info tab.  If you need to keep someone out whom you've just kicked, and they know the channel details, you need to change the channel name and password in all co-guilds.
