### ISSUE TITLE
GreenWall.lua:195 attempt to index global 'addon' (a nil value)

### ISSUE THREAD

**Issue by StupidGenius** [AIE-Guild/GreenWall#218]
![image](https://github.com/user-attachments/assets/9b43ea56-9e5b-4785-875a-f31ec845a4a2)
```
Stack: Interface/AddOns/GreenWall/GreenWall.lua:195 attempt to index global 'addon' (a nil value) 
[string "=[C]"]:?
[string "@Interface/AddOns/GreenWall/GreenWall.lua"]:195 in function 'GreenWall_OnLoad'
[string "*GreenWall.xml:32_OnLoad"]:1 in function <[string "*GreenWall.xml:32_OnLoad"]:1>
```
This was reported from a guild officer, but I am unable to reproduce it, or see the error myself.

Regardless, the cause is clear. I had thought the ` addon.settingsCategory = category`, was required for the new interface options for #216 , but it was not and is causing this error message.

**Comment by mrogaski** [comment]
Fixed in 1.11.13.
