### ISSUE TITLE
Seeing <-> symbols and the message appearing twice under 1.5.1

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/GreenWall#35]
From four_paws:

> We have had GreenWall running for a month or so, no problem (1.4.1). However, since 6..0.2 went live and we updated to GW 1.5.1 we are seeing <-> symbols and the message appearing twice. On the confederation guild we are not seeing the guild short name, but <-> instead but one copy of message.
> 
> Is this a problem with 1.5.1 or has the configuration changed. The old version is no-longer on the web to download for experimenting... my instinct is that 1.4.1 is ok?

**Comment by JaeveKJ** [comment]
Hi, I'm trying to connect two guilds on the same server.  One guild(DoW) the gchat is working as intended, but the other guild(LaB) I'm seeing the double message problem only from other member of LaB, but DoW is fine.  

GW:c:topSekritChan:pencil
GW:v:1.5.4
GW:p:Den of Wolves-Kil'Jaeden:DoW
GW:p:Like a Boss-Kil'Jaeden:LaB

**Comment by mrogaski** [comment]
The names are case-sensitive and the name of the other guild appears to be [Like A Boss-Kil'Jaeden](http://us.battle.net/wow/en/guild/kiljaeden/Like_A_Boss/).

**Comment by mrogaski** [comment]
Issue resolved by fully qualifying guild name.
