### ISSUE TITLE
[1.6.0-beta.1] LUA error ; bad argument #3 to format (Utility.lua:100)

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#61]
Date: 2015-02-18 13:26:19
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GreenWall\Utility.lua line 100:
   bad argument #3 to 'format' (string expected, got no value)
Debug:
   [C]: ?
   [C]: format()
   GreenWall\Utility.lua:100: Debug()
   GreenWall\Channel.lua:384: tl_receive()
   GreenWall\Channel.lua:344: receive()
   GreenWall\GreenWall.lua:404: GreenWall_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1

**Comment by ashayo** [comment]
Figured out why ; someone 'spoke' directly into the channel, presumably manually.

13:26:19 [Daztek-EarthenRing]: goodluck!
13:26:30 [Daztek-EarthenRing]: C#salus##goodluck!

**Comment by hasteur** [comment]
Thought: perhaps have the officers noticed if someone directly speaks into
the channel?
