### ISSUE TITLE
[1.6.0] Unable to disable achievement spam

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/GreenWall#75]
From casiekp on Curse:

Hello. 

> I am wondering if you have suggestions for an achievement announcement problem that our guild has been having. This issue does not affect everyone but does affect multiple people in our 9000+ toon guild. myself included. 

> Before 6.1 this wasn't an issue and I am using the most up to date version of Greenwall. I have uninstalled and reinstalled, disabled all other add ons and it is still happening.

> The issue is this: Even with Co-Guild achievement announcements turned off I still get annoucements for all guilds. I have this turned off through /gw achevements off and through the interface options. It is not only posting new achievements but also old achieves.  http://imgur.com/DHsQrs9

> It would be one thing if it was showing just for my subguild but I can see it for all 10 guilds and as an officer it makes it difficult to monitor the guild appropiatly as all I see is achieve spam. 

> Thanks for the wonderful addon, I am confident that you will be able to resolve our issue.

**Comment by ashayo** [comment]
"2015-03-01 12:18:50 -- event logging turned ON.", -- [1]
	"2015-03-01 12:19:04 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_GUILD_ACHIEVEMENT", -- [2]
	"2015-03-01 12:19:04 -- [debug/5@GreenWall.lua:367(GreenWall_OnEvent)] event=CHAT_MSG_GUILD_ACHIEVEMENT, sender=Murpy-AeriePeak, message=%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-076754AF:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [3]
	"2015-03-01 12:19:04 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_GUILD_ACHIEVEMENT", -- [4]
	"2015-03-01 12:19:04 -- [debug/5@GreenWall.lua:367(GreenWall_OnEvent)] event=CHAT_MSG_GUILD_ACHIEVEMENT, sender=Fiveinchfun-AeriePeak, message=%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-07A46D07:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [5]
	"2015-03-01 12:19:05 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_CHANNEL", -- [6]
	"2015-03-01 12:19:05 -- [debug/4@Channel.lua:386(tl_receive)] channel=4, sender=Fiveinchfun-AeriePeak, segment=A#mobus##%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-07A46D07:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [7]
	"2015-03-01 12:19:05 -- [debug/5@Channel.lua:408(tl_receive)] opcode=A, guild_id=mobus, message=%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-07A46D07:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [8]
	"2015-03-01 12:19:05 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_CHANNEL", -- [9]
	"2015-03-01 12:19:05 -- [debug/4@Channel.lua:386(tl_receive)] channel=4, sender=Murpy-AeriePeak, segment=A#mobus##%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-076754AF:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [10]
	"2015-03-01 12:19:05 -- [debug/5@Channel.lua:408(tl_receive)] opcode=A, guild_id=mobus, message=%s has earned the achievement |cffffff00|Hachievement:3007:Player-1426-076754AF:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Crazy Cat Lady (25 player)]|h|r!", -- [11]
	"2015-03-01 12:19:15 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=GUILD_ROSTER_UPDATE", -- [12]
	"2015-03-01 12:19:15 -- [debug/5@Config.lua:164(load)] configuration valid; skipping.", -- [13]
	"2015-03-01 12:19:15 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=GUILD_ROSTER_UPDATE", -- [14]
	"2015-03-01 12:19:15 -- [debug/5@Config.lua:164(load)] configuration valid; skipping.", -- [15]
	"2015-03-01 12:19:16 -- [debug/5@GreenWall.lua:302(GreenWall_OnEvent)] event occurred; event=CHAT_MSG_CHANNEL", -- [16]
	"2015-03-01 12:19:16 -- [debug/4@Channel.lua:386(tl_receive)] channel=4, sender=Baxov-AeriePeak, segment=A#sha##%s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [17]
	"2015-03-01 12:19:16 -- [debug/5@Channel.lua:408(tl_receive)] opcode=A, guild_id=sha, message=%s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [18]
	"2015-03-01 12:19:16 -- [debug/3@Channel.lua:367(receive)] channel=4, type=2, sender=Baxov-AeriePeak, message=%s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [19]
	"2015-03-01 12:19:16 -- [debug/5@Channel.lua:375(al_decode)] type=2, message=%s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [20]
	"2015-03-01 12:19:16 -- [debug/5@Chat.lua:33] type=2, guild_id=sha, #content=1, #arglist=16", -- [21]
	"2015-03-01 12:19:16 -- [debug/4@Chat.lua:103(ReplicateMessage)] event=GUILD_ACHIEVEMENT, guild_id=sha, message=%s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [22]
	"2015-03-01 12:19:16 -- [debug/5@Chat.lua:121(ReplicateMessage)] frame=ChatFrame1, event=GUILD_ACHIEVEMENT, sender=Baxov-AeriePeak, message=<sha> %s has earned the achievement |cffffff00|Hachievement:9457:Player-1426-07DCA76C:1:2:28:15:4294967295:4294967295:4294967295:4294967295|h[Blackwater Whiptail Angler]|h|r!", -- [23]
	"2015-03-01 12:19:20 -- [debug/3@GreenWall.lua:158] command=log, args=off", -- [24]
