### ISSUE TITLE
[1.7-alpha] Input validation required for encrypted data

### ISSUE THREAD

**Issue by ashayo** [AIE-Guild/GreenWall#91]
Malicious users can cause GW errors - eg
/2 E#myguild##blahblah

Date: 2015-12-28 21:58:19
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GreenWall\Lib\Base64BCA.lua line 154:
   Invalid input, expected type string but got: nil as a: nil
Debug:
   [C]: assert()
   GreenWall\Lib\Base64BCA.lua:154: decode()
   GreenWall\Channel.lua:410: al_decode()
   GreenWall\Channel.lua:390: receive()
   GreenWall\GreenWall.lua:366: GreenWall_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
(*temporary) = false
(*temporary) = "Invalid input, expected type string but got: nil as a: nil"

**Comment by mrogaski** [comment]
Good catch!
