### ISSUE TITLE
Greenwall breaks when ran with Prat addon

### ISSUE THREAD

**Issue by Incarceron** [AIE-Guild/GreenWall#95]
Running the very popular chat addon Prat seems to break Greenwall. It throws tons of errors and breaks up the messages into boxes and symbols.

Not fun.

**Comment by mrogaski** [comment]
What version of GreenWall and Prat are you using?

**Comment by Incarceron** [comment]
Sorry, I forgot I wrote this. I'm using the latest version of both.

**Comment by mrogaski** [comment]
Would you be able to capture some debugging information?  I haven't been able to reproduce the issue.

https://github.com/AIE-Guild/GreenWall/wiki/Collecting-Debugging-Information

**Comment by Incarceron** [comment]
Unfortunately, I can't. My gametime recently ran out and I'm not in a position where I can afford to renew it. Sorry.
